name: 🚀 Feature Request
description: Suggest an idea, feature, or enhancement
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a feature request! Please let us know what you're trying to do

  - type: textarea
    attributes:
      label: Describe the solution
      description: A clear description of what you want to happen.
    validations:
      required: true